### ISSUE TITLE
Dont use `Math.random`

### ISSUE THREAD

**Issue by theKashey** [alexkrolick/use-conditional-effect#3]
Random is so random, that could produce the same value twice. Just return a "new" object, instead of a "unique" number. It will trigger effect with a less luck involved.
```js
function getArtificialDependency() {
  return {}
}
```

**Comment by alexkrolick** [comment]
LGTM, that's the main thing I was looking to change!

**Comment by alexkrolick** [comment]
Fixed in v1.0.1
